SIGNUP_SELECT_INDUSTRY = 'user_organization_attributes_industry'
SIGNUP_SELECT_COUNTRY  = 'country'
SIGNUP_SELECT_STATE    = 'organization_state'

SIGNUP_INPUT_OTHER_INDUSTRY = 'user_organization_attributes_other_industry'
SIGNUP_INPUT_EMAIL          = 'user_email'
SIGNUP_INPUT_PASSWORD       = 'user_password'
SIGNUP_INPUT_PASSWORD_CONF  = 'user_password_confirmation'
SIGNUP_INPUT_F_NAME         = 'user_first_name'
SIGNUP_INPUT_L_NAME         = 'user_last_name'
SIGNUP_INPUT_PHONE          = 'user_phone'
SIGNUP_INPUT_MOBILE         = 'user_mobile_phone'
SIGNUP_INPUT_WORK_PHONE     = 'user_work_phone'
SIGNUP_INPUT_ORG_NAME       = 'user_organization_attributes_name'
SIGNUP_INPUT_ORG_ADD1       = 'user_organization_attributes_address1'
SIGNUP_INPUT_ORG_ADD2       = 'user_organization_attributes_address2'
SIGNUP_INPUT_ORG_CITY       = 'user_organization_attributes_city'
SIGNUP_INPUT_ORG_ZIP        = 'user_organization_attributes_zip'
SIGNUP_INPUT_ORG_WEBSITE    = 'user_organization_attributes_website'
SIGNUP_INPUT_ORG_PHONE      = 'user_organization_attributes_work_phone'
SIGNUP_INPUT_ORG_MOBILE     = 'user_organization_attributes_mobile'
SIGNUP_INPUT_ORG_EMAIL      = 'user_organization_attributes_email'


SIGNUP_BTN_SIGN_UP = 'sign_up_btn'