service_call:
  forms:
    subcontractor_status:
      mark_as_settled:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      subcon_confirmed:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      subcon_marked_as_settled:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      confirm_settled:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      settle:
#        form_classes: ""
        button_classes: "btn btn-large btn-primary"
      clear:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-success"

    provider_status:
      mark_as_settled:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-primary"
      subcon_confirmed:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      subcon_marked_as_settled:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-primary"
      confirm_settled:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      settle:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      clear:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-success"
    status:
      accept:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      un_accept:
#        form_classes: "red-button"
        button_classes: "btn btn-large btn-danger"
      reject:
#        form_classes: "red-button"
        button_classes: "btn btn-large btn-danger"
      transfer:
#        form_classes: "blue-button"
        button_classes: "btn btn-primary"
      cancel_transfer:
#        form_classes: "red-button"
        button_classes: "btn btn-large btn-danger"
      cancel:
#        form_classes: "red-button"
        button_classes: "btn btn-large btn-danger"
      close:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      activate:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      un_cancel:
#        form_classes: "red-button"
        button_classes: "btn btn-large btn-primary"
    work_status:
      start:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      accept:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      reject:
#        form_classes: "red-button"
        button_classes: "btn btn-large btn-danger"
      un_accept:
#        form_classes: "red-button"
        button_classes: "btn btn-large btn-primary"
      dispatch:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      reset:
#        form_classes: ""
        button_classes: "btn btn-large btn-info"
      complete:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
    billing_status:
      invoice:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      subcon_invoiced:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      provider_invoiced:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      overdue:
#        form_classes: "red-button"
        button_classes: "btn btn-large btn-danger"
      collect:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      deposited:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      paid:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      clear:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-primary"
      subcon_collected:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      subcon_deposited:
#        form_classes: "green-button"
        button_classes: "btn btn-large btn-success"
      confirm_deposit:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      prov_confirmed_deposit:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      provider_collected:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      deposit_to_prov:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"
      employee_deposit:
#        form_classes: "blue-button"
        button_classes: "btn btn-large btn-primary"


  states:
    status:
      new: "status_blue"
      open: "status_blue"
      transferred: "status_blue"
      closed: "status_green"
      canceled: "status_red"
      accepted: "status_blue"
      rejected: "status_red"
    work_status:
      pending: "status_grey"
      dispatched: "status_blue"
      in_progress: "status_blue"
      accepted: "status_blue"
      rejected: "status_red"
      done: "status_green"
    subcontractor_status:
      na: "status_grey"
      pending: "status_grey"
      claim_settled: "status_blue"
      claimed_as_settled: "status_blue"
      settled: "status_blue"
      cleared: "status_green"
    provider_status:
      pending: "status_grey"
      claim_settled: "status_blue"
      claimed_as_settled: "status_blue"
      settled: "status_blue"
      cleared: "status_green"
    billing_status:
      na:  "status_grey"
      pending: "status_grey"
      invoiced: "status_blue"
      collected_by_employee: "status_blue"
      collected: "status_blue"
      deposited_to_prov: "status_blue"
      deposited: "status_green"
      invoiced_by_subcon: "status_blue"
      collected_by_subcon: "status_blue"
      subcon_claim_deposited: "status_blue"
      invoiced_by_prov: "status_blue"
      overdue: "status_red"
      paid: "status_blue"
      cleared: "status_green"
      rejected: "status_red"

